services:
  hipsdontlie:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: Development
    container_name: hipsdontlie-app
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_RUNNING_IN_CONTAINER: "true"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"

      JwtSettings__SecretKey: "C6821CD46246E81E9B481CD9D4D9A123C6821CD46246E81E9B481CD9D4D9A123"
      JwtSettings__Issuer: "HipsDontLie"
      JwtSettings__Audience: "HipsDontLieApp"

    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
