services:
  hipsdontlie:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: Development
    container_name: hipsdontlie-app
    expose:
      - "80"
      - "443"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_RUNNING_IN_CONTAINER: "true"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      JwtSettings__SecretKey: "C6821CD46246E81E9B481CD9D4D9A123C6821CD46246E81E9B481CD9D4D9A123"
      JwtSettings__Issuer: "HipsDontLie"
      JwtSettings__Audience: "HipsDontLieApp"
      ConnectionStrings__DefaultConnection: "server=db;port=3306;database=hips;user=appuser;password=apppass"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8
    container_name: hipsdontlie-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: hips
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: hipsdontlie-nginx
    depends_on:
      - hipsdontlie
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

volumes:
  db_data:
