using HipsDontLie.Models;
using HipsDontLie.Repository;
using HipsDontLie.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Tokens;
using Moq;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;

namespace HipsDontLie.Test
// <summary>
// Unit tests for the AuthService class.
// </summary>
// <remarks>
// This test was generated by Claude AI.
{
    [TestFixture]
    public class AuthServiceTests
    {
        private Mock<IUserRepository> _mockUserRepository;
        private IConfiguration _configuration;
        private AuthService _authService;
        private Mock<UserManager<User>> _mockUserManager;
        private Mock<RoleManager<IdentityRole<int>>> _mockRoleManager;
        private Mock<SignInManager<User>> _mockSignInManager;

        [SetUp]
        public void Setup()
        {
            // Create configuration with in-memory values for testing
            var inMemorySettings = new Dictionary<string, string> {
                {"JwtSettings:SecretKey", "TestSecretKeyWithAtLeast32Characters!!"},
                {"JwtSettings:Issuer", "TestIssuer"},
                {"JwtSettings:Audience", "TestAudience"},
                {"ASPNETCORE_ENVIRONMENT", "Development"}
            };

            _configuration = new ConfigurationBuilder()
                .AddInMemoryCollection(inMemorySettings)
                .Build();

            // Create mock repositories
            _mockUserManager = MockUserManager();
            _mockRoleManager = MockRoleManager();
            _mockUserRepository = new Mock<IUserRepository>();
            _mockSignInManager = MockSignInManager();

            _mockUserManager
            .Setup(m => m.GetRolesAsync(It.IsAny<User>()))
            .ReturnsAsync(new List<string>() { "Participant", "Instructor" });

            // Create auth service with real configuration but mock managers
            _authService = new AuthService(_configuration, _mockUserManager.Object, _mockRoleManager.Object, _mockSignInManager.Object);
        }



        #region RegisterUserAsync Tests

        [Test]
        public async Task RegisterUserAsync_NewUser_ReturnsUserCreated()
        {
            // Arrange
            string email = "user@example.com";
            string username = "user";
            string password = "Password123";
            string displayName = "Tester";

            _mockUserManager.Setup(m => m.FindByEmailAsync(email))
                .ReturnsAsync((User?)null);

            _mockUserManager
                .Setup(m => m.CreateAsync(
                    It.Is<User>(u =>
                        u.Email == email &&
                        u.UserName == username &&
                        u.DisplayName == displayName &&
                        u.EmailConfirmed == true
                    ),
                    password))
                .ReturnsAsync(IdentityResult.Success);

            _mockRoleManager.Setup(r => r.RoleExistsAsync("Participant"))
                .ReturnsAsync(true);

            _mockUserManager.Setup(m => m.AddToRoleAsync(It.Is<User>(u => u.Email == email),"Participant"))
                .ReturnsAsync(IdentityResult.Success);

            // Act
            var result = await _authService.RegisterUserAsync(email, username, displayName, password);

            // Assert
            Assert.That(result, Is.EqualTo(AuthStatus.TestUserCreated));
            _mockUserManager.Verify(m => m.FindByEmailAsync(email), Times.Once);
            _mockUserManager.Verify(
                m => m.CreateAsync(It.IsAny<User>(), password),
                Times.Once);
            _mockRoleManager.Verify(r => r.RoleExistsAsync("Participant"), Times.Once);
            _mockUserManager.Verify(
                m => m.AddToRoleAsync(It.IsAny<User>(), "Participant"),
                Times.Once);
        }

        [Test]
        public async Task RegisterUserAsync_ExistingUser_ReturnsUserExists()
        {
            // Arrange
            string email = "user@example.com";
            string username = "existing";
            string password = "Password123";
            string displayName = "Tester";

            var existingUser = new User
            {
                Id = 1,
                Email = email,
                UserName = username
            };

            _mockUserManager.Setup(m => m.FindByEmailAsync(email)).ReturnsAsync(existingUser);

            // Act
            var result = await _authService.RegisterUserAsync(email, username, displayName, password);

            // Assert
            Assert.That(result, Is.EqualTo(AuthStatus.UserExists));
            _mockUserManager.Verify(m => m.CreateAsync(It.IsAny<User>(), It.IsAny<string>()), Times.Never);
            _mockRoleManager.Verify(m => m.RoleExistsAsync(It.IsAny<string>()), Times.Never);
            _mockUserManager.Verify(m => m.AddToRoleAsync(It.IsAny<User>(), It.IsAny<string>()), Times.Never);
        }

        [Test]
        public async Task RegisterUserAsync_WeakPassword_ReturnsWeakPassword()
        {
            // Arrange
            string email = "user@example.com";
            string username = "user";
            string password = "weak"; // Too short, missing requirements
            string displayName = "Tester";

            _mockUserRepository.Setup(r => r.GetUserByEmailAsync(email)).ReturnsAsync((User)null);

            // Act
            var result = await _authService.RegisterUserAsync(email, username, displayName, password);

            // Assert
            Assert.That(result, Is.EqualTo(AuthStatus.WeakPassword));
            _mockUserRepository.Verify(r => r.AddUserAsync(It.IsAny<User>()), Times.Never);
        }

        [Test]
        public async Task RegisterUserAsync_TestEmail_SetsEmailVerifiedTrue()
        {
            // Arrange
            string email = "user@example.com";
            string username = "user";
            string password = "Password123";
            string displayName = "Tester";

            _mockUserManager
                .Setup(m => m.FindByEmailAsync(email))
                .ReturnsAsync((User?)null);

            _mockUserManager
                .Setup(m => m.CreateAsync(
                    It.Is<User>(u =>
                        u.Email == email &&
                        u.UserName == username &&
                        u.DisplayName == displayName &&
                        u.EmailConfirmed == true
                    ),
                    password))
                .ReturnsAsync(IdentityResult.Success);

            _mockRoleManager.Setup(r => r.RoleExistsAsync("Participant"))
                .ReturnsAsync(true);

            _mockUserManager
                .Setup(m => m.AddToRoleAsync(
                    It.Is<User>(u => u.Email == email),
                    "Participant"))
                .ReturnsAsync(IdentityResult.Success);

            // Act
            var result = await _authService.RegisterUserAsync(email, username, displayName, password);

            // Assert
            Assert.That(result, Is.EqualTo(AuthStatus.TestUserCreated));
            _mockUserManager.Verify(m => m.FindByEmailAsync(email), Times.Once);
            _mockUserManager.Verify(m => m.CreateAsync(It.IsAny<User>(), password),Times.Once);
            _mockRoleManager.Verify(r => r.RoleExistsAsync("Participant"), Times.Once);
            _mockUserManager.Verify(m => m.AddToRoleAsync(It.IsAny<User>(), "Participant"), Times.Once);
        }

        #endregion

        #region DeleteUserAsync Tests

        [Test]
        public async Task DeleteUserAsync_ValidId_ReturnsTrue()
        {
            // Arrange
            int userId = 1;
            string email = "user@example.com";
            string userName = "user";

            var user = new User
            {
                Id = userId,
                Email = email,
                UserName = userName
            };

            _mockUserManager
                .Setup(m => m.FindByIdAsync(userId.ToString()))
                .ReturnsAsync(user);

            _mockUserManager
                .Setup(m => m.DeleteAsync(user))
                .ReturnsAsync(IdentityResult.Success);

            // Act
            var result = await _authService.DeleteUserAsync(userId);

            // Assert
            Assert.IsTrue(result);
            _mockUserManager.Verify(m => m.FindByIdAsync(userId.ToString()), Times.Once);
            _mockUserManager.Verify(m => m.DeleteAsync(user), Times.Once);
        }

        [Test]
        public async Task DeleteUserAsync_InvalidId_ReturnsFalse()
        {
            // Arrange
            int userId = 999;

            _mockUserManager
                .Setup(m => m.FindByIdAsync(userId.ToString()))
                .ReturnsAsync((User?)null);

            // Act
            var result = await _authService.DeleteUserAsync(userId);

            // Assert
            Assert.IsFalse(result);
            _mockUserManager.Verify(m => m.DeleteAsync(It.IsAny<User>()), Times.Never);
        }

        [Test]
        public async Task DeleteUserAsync_ValidEmail_FindsUserAndDeletes()
        {
            // Arrange
            string email = "user@example.com";
            int userId = 1;

            var user = new User
            {
                Id = userId,
                Email = email,
                UserName = "user"
            };

            _mockUserManager
                .Setup(m => m.FindByEmailAsync(email))
                .ReturnsAsync(user);

            _mockUserManager
                .Setup(m => m.DeleteAsync(user))
                .ReturnsAsync(IdentityResult.Success);

            // Act
            var result = await _authService.DeleteUserAsync(0, email);

            // Assert
            Assert.IsTrue(result);
            _mockUserManager.Verify(m => m.FindByEmailAsync(email), Times.Once);
            _mockUserManager.Verify(m => m.DeleteAsync(user), Times.Once);
        }

        [Test]
        public async Task DeleteUserAsync_InvalidEmail_ReturnsFalse()
        {
            // Arrange
            string email = "nonexistent@example.com";
            
            _mockUserRepository.Setup(r => r.GetUserByEmailAsync(email))
                .ReturnsAsync((User)null);

            // Act
            var result = await _authService.DeleteUserAsync(0, email);

            // Assert
            Assert.IsFalse(result);
            _mockUserRepository.Verify(r => r.DeleteUserAsync(It.IsAny<int>()), Times.Never);
        }

        #endregion

        #region SendEmailVerificationAsync Tests

        [Test]
        public async Task SendEmailVerificationAsync_UserNotFound_ReturnsFalse()
        {
            // Arrange
            string email = "nonexistent@example.com";
            _mockUserRepository.Setup(r => r.GetUserByEmailAsync(email))
                .ReturnsAsync((User)null);

            // Act
            var result = await _authService.SendEmailVerificationAsync(email);

            // Assert
            Assert.IsFalse(result);
        }

        #endregion

        #region ConfirmEmailAsync Tests

        [Test]
        public async Task ConfirmEmailAsync_ValidToken_ReturnsTrue()
        {
            // Arrange
            int userId = 1;
            string email = "user@example.com";
            string username = "user";
            string token = "dummy-email-confirmation-token";

            var user = new User
            {
                Id = userId,
                Email = email,
                UserName = username
            };

            _mockUserManager
                .Setup(m => m.FindByIdAsync(userId.ToString()))
                .ReturnsAsync(user);

            _mockUserManager
                .Setup(m => m.ConfirmEmailAsync(user, token))
                .ReturnsAsync(IdentityResult.Success);

            // Act
            var result = await _authService.ConfirmEmailAsync(userId, token);

            // Assert
            Assert.IsTrue(result);
            _mockUserManager.Verify(m => m.FindByIdAsync(userId.ToString()), Times.Once);
            _mockUserManager.Verify(m => m.ConfirmEmailAsync(user, token), Times.Once);
        }

        [Test]
        public async Task ConfirmEmailAsync_InvalidToken_ReturnsFalse()
        {
            // Arrange
            string invalidToken = "invalid.token.string";
            int userId = 1;

            // Act
            var result = await _authService.ConfirmEmailAsync(userId, invalidToken);

            // Assert
            Assert.IsFalse(result);
            _mockUserRepository.Verify(r => r.ConfirmEmailAsync(It.IsAny<int>()), Times.Never);
        }

        #endregion

        #region AuthenticateUserAsync Tests

        [Test]
        public async Task AuthenticateUserAsync_ValidCredentials_ReturnsToken()
        {
            // Arrange
            string email = "user@example.com";
            string password = "Password123";

            var user = new User
            {
                Id = 1,
                Email = email,
                UserName = email,
                EmailConfirmed = true
            };

            _mockUserManager
                .Setup(m => m.FindByEmailAsync(email))
                .ReturnsAsync(user);

            _mockUserManager
                .Setup(m => m.CheckPasswordAsync(user, password))
                .ReturnsAsync(true);

            // Act
            var token = await _authService.AuthenticateUserAsync(email, password);

            // Assert
            Assert.IsNotNull(token);
            Assert.IsNotEmpty(token);
        }

        [Test]
        public async Task AuthenticateUserAsync_UserNotFound_ReturnsNull()
        {
            // Arrange
            string email = "nonexistent@example.com";
            string password = "Password123";

            _mockUserRepository.Setup(r => r.GetUserByEmailAsync(email))
                .ReturnsAsync((User)null);

            // Act
            var token = await _authService.AuthenticateUserAsync(email, password);

            // Assert
            Assert.IsNull(token);
        }

        [Test]
        public async Task AuthenticateUserAsync_IncorrectPassword_ReturnsNull()
        {
            // Arrange
            string email = "user@example.com";
            string correctPassword = "Password123";
            string wrongPassword = "WrongPassword123";
            string hashedPassword = BCrypt.Net.BCrypt.HashPassword(correctPassword);

            _mockUserRepository.Setup(r => r.GetUserByEmailAsync(email))
                .ReturnsAsync(new User 
                { 
                    Id = 1, 
                    Email = email, 
                    PasswordHash = hashedPassword,
                    EmailConfirmed = true 
                });

            // Act
            var token = await _authService.AuthenticateUserAsync(email, wrongPassword);

            // Assert
            Assert.IsNull(token);
        }

        [Test]
        public async Task AuthenticateUserAsync_EmailNotVerified_ReturnsNull()
        {
            // Arrange
            string email = "user@example.com";
            string password = "Password123";
            string hashedPassword = BCrypt.Net.BCrypt.HashPassword(password);

            _mockUserRepository.Setup(r => r.GetUserByEmailAsync(email))
                .ReturnsAsync(new User 
                { 
                    Id = 1, 
                    Email = email, 
                    PasswordHash = hashedPassword,
                    EmailConfirmed = false // Not verified
                });

            // Act
            var token = await _authService.AuthenticateUserAsync(email, password);

            // Assert
            Assert.IsNull(token);
        }

        #endregion

        #region Helpers
        private static Mock<UserManager<User>> MockUserManager()
        {
            var store = new Mock<IUserStore<User>>();
            return new Mock<UserManager<User>>(
                store.Object,
                null, null, null, null, null, null, null, null
            );
        }

        private static Mock<SignInManager<User>> MockSignInManager()
        {
            var userManager = MockUserManager().Object;

            var contextAccessor = new Mock<IHttpContextAccessor>();
            contextAccessor.Setup(x => x.HttpContext).Returns(new DefaultHttpContext());

            var claimsFactory = new Mock<IUserClaimsPrincipalFactory<User>>();

            var options = new Mock<IOptions<IdentityOptions>>();
            options.Setup(o => o.Value).Returns(new IdentityOptions());

            var logger = new Mock<ILogger<SignInManager<User>>>();

            var schemes = new Mock<IAuthenticationSchemeProvider>();

            var confirmation = new Mock<IUserConfirmation<User>>();

            return new Mock<SignInManager<User>>(
                userManager,
                contextAccessor.Object,
                claimsFactory.Object,
                options.Object,
                logger.Object,
                schemes.Object,
                confirmation.Object
            );
        }


        private static Mock<RoleManager<IdentityRole<int>>> MockRoleManager()
        {
            var store = new Mock<IRoleStore<IdentityRole<int>>>();
            return new Mock<RoleManager<IdentityRole<int>>>(
                store.Object,
                null, null, null, null
            );
        }
        #endregion
    }
}